var N = null;var sourcesIndex = {};
sourcesIndex["matrix_sdk"] = {"name":"","dirs":[{"name":"event_handler","files":["mod.rs"]},{"name":"room","files":["common.rs","invited.rs","joined.rs","left.rs","mod.rs"]}],"files":["client.rs","device.rs","error.rs","http_client.rs","lib.rs","room_member.rs","sas.rs","verification_request.rs"]};
sourcesIndex["matrix_sdk_appservice"] = {"name":"","files":["actix.rs","error.rs","lib.rs"]};
sourcesIndex["matrix_sdk_base"] = {"name":"","dirs":[{"name":"rooms","files":["members.rs","mod.rs","normal.rs"]},{"name":"store","dirs":[{"name":"sled_store","files":["mod.rs","store_key.rs"]}],"files":["ambiguity_map.rs","memory_store.rs","mod.rs"]}],"files":["client.rs","error.rs","lib.rs","session.rs"]};
sourcesIndex["matrix_sdk_common"] = {"name":"","files":["deserialized_responses.rs","executor.rs","lib.rs","locks.rs"]};
sourcesIndex["matrix_sdk_crypto"] = {"name":"","dirs":[{"name":"file_encryption","files":["attachments.rs","key_export.rs","mod.rs"]},{"name":"identities","files":["device.rs","manager.rs","mod.rs","user.rs"]},{"name":"olm","dirs":[{"name":"group_sessions","files":["inbound.rs","mod.rs","outbound.rs"]},{"name":"signing","files":["mod.rs","pk_signing.rs"]}],"files":["account.rs","mod.rs","session.rs","utility.rs"]},{"name":"session_manager","files":["group_sessions.rs","mod.rs","sessions.rs"]},{"name":"store","files":["caches.rs","memorystore.rs","mod.rs","pickle_key.rs","sled.rs"]},{"name":"verification","dirs":[{"name":"sas","files":["event_enums.rs","helpers.rs","inner_sas.rs","mod.rs","sas_state.rs"]}],"files":["machine.rs","mod.rs","requests.rs"]}],"files":["error.rs","key_request.rs","lib.rs","machine.rs","requests.rs","utilities.rs"]};
sourcesIndex["matrix_sdk_test"] = {"name":"","dirs":[{"name":"test_json","files":["events.rs","members.rs","mod.rs","sync.rs"]}],"files":["lib.rs"]};
sourcesIndex["matrix_sdk_test_macros"] = {"name":"","files":["lib.rs"]};
createSourceSidebar();
